### ISSUE TITLE
Escape to quit file picker

### ISSUE THREAD

**Issue by acroz** [srstevenson/vim-picker#1]
Would it be reasonable to map Escape to close the file picker by default? I intuitively try to use it to quit the picker - maybe it might be a sensible default?

**Comment by srstevenson** [comment]
Thanks for the suggestion! This is implemented in 29a8af50eda12d66e8e2af63489ce4607c2064fa.

This only works in Neovim, where we use the embedded terminal emulator. In Vim you can quit the selector by sending `SIGINT` with <kbd>Ctrl</kbd>+<kbd>C</kbd> (which also works in Neovim and a shell).

Also, the filetype of the Neovim terminal buffer is now set to `picker` so that you can add custom mappings. For example, to print the working directory on <kbd>Space</kbd>+<kbd>p</kbd>:

```viml
autocmd FileType picker tnoremap <buffer> <silent> <Space>p <C-\><C-n>:pwd<CR>
```
