### ISSUE TITLE
Consider using the current file for context

### ISSUE THREAD

**Issue by svenstaro** [srstevenson/vim-picker#14]
Hi, cool plugin. I tested it a bit and compared it to ctrlp with [cpsm](https://github.com/nixprime/cpsm). What I found was that vim-picker doesn't take into account the current file. Do you think this might be a good idea? I think just using nothing as a base for searching is a worse guess than the current file. If you're in C code, for instance, you often want to take into account the current file as you might want to switch between `.c` and `.h` files, for instance.

EDIT: I did a little bit of researching and it seems that this should be really easy to do if you use `fzy -q <current file>`.

**Comment by boxofrox** [comment]
Not sure I follow.

You want to be able to pop open vim-picker and "quickly" select a file of the same name but with a different extension only?

Other than the c example given, I can't think of another use for this feature.  Given the narrow focus of this, I guess that begs the question, why put this in vim-picker instead of its own vimscript?

```vim
let s:extensionMap = {
      \'c': 'h',
      \'h': 'c',
      \}

function! s:openFileWithExt (filepath, newExt)
  let l:fileroot  = fnamemodify(a:filepath, ':.:r')
  let l:newfile = fnameescape(l:fileroot . '.' . a:newExt)
  execute 'edit' l:newfile
endfunction

function! s:openFileByContext (filepath)
  let l:ext = fnamemodify(a:filepath, ':e')

  if ! has_key(s:extensionMap, l:ext)
    return
  endif

  call s:openFileWithExt(a:filepath, get(s:extensionMap, l:ext))
endfunction

command -bar OpenFileByContext call s:openFileByContext(expand('%'))

" usage:  after sourcing this file, open any c header/source file and run the following
"         ex command.
" :OpenFileByContext
```

**Comment by svenstaro** [comment]
No, that's much too narrow. My link to cpsm should make the utility and scope quite clear.

There is some further discussion here: https://github.com/junegunn/fzf.vim/issues/492

The general idea is to give the picker a better starting guess as to what kind of file you want. I only mentioned one example but you also might imagine switching between test cases and corresponding code or between files in the same subtree.

The picker currently doesn't get a good starting guess at all and just keeps starting at the same point every time which is a poor default. The picker could be even more helpful by guessing that you might want something that is a bit similar to your current file name if given the choice between otherwise similarly ranked candidates. A bit of "current file bias", if you will.

Check out the benchmarks in the cpsm Readme and it should become more clear what I mean.

**Comment by boxofrox** [comment]
The cpsm README mentions:

> Only cpsm and fzf do any ranking; cpsm is falling back on the shortest filename in the closest directory to the current file (which is the repository's root), while fzf picks the lexicographically lowest filename in the root directory.

If you want to rank matches closest to the current file, then that's a limitation of the underlying tool used (e.g. fzy).  `fzy -q` is a bit of a hack to achieve this.

You might find a terminal fuzzy search tool similar to [`fzy`][fzy], [`pick`][pick], or [`selecta`][selecta], or write one, or patch one of those, that ranks matches nearest some specified file and that could be integrated into vim-picker.

I was in the middle writing this post when you replied, @svenstaro.  Now that I've read it...

cpsm seems to focus on matching files only, whereas vim-picker exposes the functionality inside vim of the three tools I just mentioned, and those tools are just "interactive Unix [filters] for [the] command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc." \[[1][fzf]].  They only work with and understand text.

\[1]: https://github.com/junegunn/fzf

I'd still recommend finding an interactive Unix filter that behaves like cpsm given a list of files and a list of open files and a list of whatever it might use to customize its search behavior, and then create a PR to add a configuration option for vim-picker to use that utility instead of `fzy`, `pick`, or `selecta` when picking files.  This aligns nicely with the cpsm as a matcher for Ctrl-P; the utility would be a matcher for vim-picker.  Plus, if I don't like the utility's ranking, I can still use `fzy`.

A new vim command that runs `fzy -q` or `selecta -q` (I dunno if `pick` has a similar option) could be added, but it's not going to give you the efficient speed increase that cpsm pursues unless you only need to edit the file extension since `-q` only populates the query (which reduces the results to one match) and now you're forced to edit that text.  Given that limitation, I'd rather use the vimscript above or even cpsm.

[fzf]: https://github.com/junegunn/fzf
[fzy]: https://github.com/jhawthorn/fzy
[pick]: https://github.com/calleerlandsson/pick
[selecta]: https://github.com/garybernhardt/selecta

**Comment by srstevenson** [comment]
Thanks for the idea @svenstaro, and your clear explanations! As @boxofrox said, weighting choices with a non-uniform prior (such as proximity to the current directory) would need to be implemented in the scoring algorithm of the filter itself.

Using `-q` with `fzy` just populates the initial query which then requires more careful editing, negating some of the benefits of using a fuzzy selector.

To navigate between pairs of files with well defined relationships (such as between `.c` and `.h`, or implementation and test), I'd recommend using [vim-projectionist](https://github.com/tpope/vim-projectionist#alternate-files).
