### ISSUE TITLE
Add support for sharkdp/fd

### ISSUE THREAD

**Issue by lithammer** [srstevenson/vim-picker#18]
https://github.com/sharkdp/fd is the new kid on the block as an alternative to `find(1)`, but obviously much faster (see benchmarks in README).

It would be nice to extend `ListFilesCommand` to check fo `fd` either between `git` and `rg`, or as first hit since it has some git filtering built in.

**Comment by srstevenson** [comment]
Thanks for the suggestion @renstrom, I hadn't come across `fd` before! I'm wary of a proliferation of conditional branches based on what tools are installed, so instead of adding `fd` I've opened #20 which makes the choice of file listing tool user configurable. To use `fd`, you can set:
```viml
let g:picker_find_executable = 'fd'
let g:picker_find_flags = '--color=never'
```
I'm going to use this configuration for a bit and decide whether to switch the default tool from `rg` to `fd`, as `fd` looks ideally suited.

**Comment by lithammer** [comment]
This is great, thanks!

**Comment by srstevenson** [comment]
@renstrom As of 6e93ac337972b334db54d873693b36deb93de7cb, `fd` is now used instead of riprgrep by default.
