### ISSUE TITLE
Keep open buffer order on opening

### ISSUE THREAD

**Issue by fbernier** [srstevenson/vim-picker#32]
Hi and thanks for this plugin.

I recently tried it and my main issue with it is that `:PickerBuffer` is not initially sorted by last opened. Once I start typing, I don't care about the order anymore but it's useful to be able to go down 1 or 2 when you know with which files you're currently working with.

**Comment by boxofrox** [comment]
I'm not sure this is worth the effort.  Here are my two cents.

1.  When I first used vim-picker, I wanted this feature, too.  But without it, I found that when I popped open `:PickerBuffer`, I already had an idea (if not the exact name) of the file I want to switch to.  Now, I type a couple letters of the filename or extension to shorten the buffer list to a handful of filenames, and from there I can browse with a few keystrokes.

    It's maybe a little more effort on my part, but it works, and doesn't complicate the fairly simple code of vim-picker by maintaining a most-recently-used (MRU) buffer list--a feature not built into Vim and a few MRU plugins \[[1](https://github.com/vim-scripts/mru.vim)] \[[2](https://github.com/vim-scripts/bufmru.vim/blob/master/plugin/bufmru.vim)] exist to fill this gap.  I switched to vim-picker because it's simple and lean.  Incorporating a MRU plugin into vim-picker, to me, is bloat.

    Now if there's a way to load a separate MRU plugin and configure vim-picker to call into that plugin to fetch its sorted buffer list with a `g:picker_bufnrs_command` that can be set in the vimrc, then there's no bloat for me to worry about.

2.  A recent update to vim-picker removed the current buffer from the `:PickerBuffer` list, because it's already front and center.

3.  Vim already supports toggling between the current buffer and the previous (aka "alternate") buffer with `<C-^>`, `<C-6>` and `:b#` \[[3](http://vim.wikia.com/wiki/Easier_buffer_switching)], which begs the question, "When Vim already has a builtin for switching to the previous buffer, what value is there in adding code to move the alternate buffer to the top of the buffer list?"  A semi-rhetorical question that suggests that what you really want is the functionality of an MRU buffer list.

\[1]: https://github.com/vim-scripts/mru.vim  
\[2]: https://github.com/vim-scripts/bufmru.vim/blob/master/plugin/bufmru.vim  
\[3]: http://vim.wikia.com/wiki/Easier_buffer_switching

**Comment by srstevenson** [comment]
@boxofrox' comment mirrors my own views here almost exactly. I'm wary of feature creep and want to keep the scope limited to fuzzy selection to keep the interface simple and the implementation lean.

If you prefer the UX model of navigating the buffer list with the cursor keys to select one to edit, there are plugins such as [BufExplorer](https://github.com/jlanzarotta/bufexplorer) and [vim-buffergator](https://github.com/jeetsukumaran/vim-buffergator) which do this. Additionally, to toggle between buffers with well defined relationships (such as between `.c` and `.h`, or implementation and test), I'd recommend using [vim-projectionist](https://github.com/tpope/vim-projectionist#alternate-files).
