### ISSUE TITLE
Lag when using mapping for PickerBuffer

### ISSUE THREAD

**Issue by zealotrush** [srstevenson/vim-picker#50]
If I activate the `PickerBuffer` command using the mapping provided in README:

```vim
nmap <unique> <leader>pb <Plug>PickerBuffer
```

I got a lag about one second before the buffer list came up. If I call the command manually by typing `:PickerBuffer` and press enter, there is no lag. And if I define the mapping as following:

```vim
nmap <unique> <leader>pb :PickerBuffer<CR>
```

Then no lags.

All other commands work fine. Only `PickerBuffer`. Is it just me?

**Comment by boxofrox** [comment]
Huh.  I see it happening in neovim 0.3.4.  I never noticed that before.

I can't jump on this right away, but will try to figure it out as I find time to spare.

**Comment by boxofrox** [comment]
I suspect neovim is waiting to see if anymore keys are pressed after `<leader>pb`.  If I type `<leader>pbb`, then the `PickerBuffer` appears without delay and a single `b` typed into the filter.

Funny thing is, I don't have any ambiguous mappings.  `<leader>pb` is unique and shouldn't require the delay.

**Comment by zealotrush** [comment]
Actually, I'm using vim 8.1.750. But I have also tried with Neovim, same problem.

I think it probably has something to do with `<Plug>PickerBuffer`, because if I replace it with `:PickerBuffer<CR>`, then there would be no lags.

**Comment by zealotrush** [comment]
Probably a dumb question: is it because of `<Plug>PickerBufferTag`?

**Comment by boxofrox** [comment]
> ...because if I replace it with :PickerBuffer<CR>, then there would be no lags.

By replace, you mean redefining the keybinding like so?

```
nmap <leader>pb :PickerBuffer<CR>
```

> Probably a dumb question: is it because of <Plug>PickerBufferTag?

Doesn't hurt to check.  Will add it to my list.

**Comment by zealotrush** [comment]
> By replace, you mean redefining the keybinding like so?

Yes. As I said in my first post.

**Comment by boxofrox** [comment]
> Yes. As I said in my first post.

Thanks.  My brain completely failed to register that portion of your post.  Thus far, I see the same behavior you're describing.

Looking into this I found \[[1](https://stackoverflow.com/a/18547013/1149718)] one can use `:execute "normal \<Plug>PickerBuffer"` to trigger the `<Plug>` mapping with an ex-command instead of a keybinding.  Leaving this here to document the technique for future troubleshooting.

> Probably a dumb question: is it because of `<Plug>PickerBufferTag`?

Yes, the delay/lag is because of `<Plug>PickerBufferTag`.  If I remove that from vim-picker, the lag disappears.

The reason is vim is waiting to see if additional keystrokes are entered.  I almost had it right earlier.  I thought vim was waiting for the user to enter keys.  It's waiting for the mapping to enter keys, because, to vim, `<Plug>PickerBuffer` is treated as a sequence of keypresses. 

For a keybinding to work, we must use `nmap` to recursively evaluate `<Plug>PickerBuffer` as a keybinding.  `nnoremap` doesn't work with `<Plug>`.  Since vim is unable to differentiate recursive keybindings from keys directly typed by the user, it waits a couple seconds to see if "Tag" is typed after `<Plug>PickerBuffer`.

@srstevenson We have a couple options to fix this.

1.  Rename `<Plug>PickerBuffer` to `<Plug>PickerBufferOnly` to remove the ambiguity.
2.  Change the convention for `<Plug>` mappings to use parenthesis to mark the beginning and end of key sequence.  e.g. `<Plug>(PickerBuffer)`, `<Plug>(PickerBufferTag)`, etc.  Inspiration from the question in \[[1](https://stackoverflow.com/a/18547013/1149718)] and \[[2](https://whileimautomaton.net/2008/09/27022735)].

I'm partial to (2). Which do you prefer?

\[1]: https://stackoverflow.com/a/18547013/1149718
\[2]: https://whileimautomaton.net/2008/09/27022735

**Comment by srstevenson** [comment]
Good sleuthing, thanks for working this out! I agree with @boxofrox, that changing `<Plug>PickerBuffer` to `<Plug>(PickerBuffer)` is the best solution. Let's do it for all of the `<Plug>` mappings, for consistency and to prevent this issue reoccuring if we add new `<Plug>` mappings with a common prefix in the future.

We can leave the mappings without parentheses as they are for backward compatibility, but remove them from the documentation and add a comment in the code saying that they're deprecated.
