### ISSUE TITLE
More split window commands

### ISSUE THREAD

**Issue by bronzehedwick** [srstevenson/vim-picker#53]
First off, great plugin, I really like the approach.

I'm wondering though if there's a reason why there aren't split commands for all the command types?

For example, there's `PickerEdit`, `PickerSplit`, `PickerVsplit`, and `PickerTabedit`, but no split options for `PickerBuffer`, and no vertical split options for `PickerTag`.

Anyway, thanks again!

**Comment by srstevenson** [comment]
This is simply because each of the original commands mirrored a builtin Vim command, but with fuzzy finding:

| Vim builtin | vim-picker replacement |
|-----|------------|
| [`:edit`](https://neovim.io/doc/user/editing.html#:edit) | `:PickerEdit` |
| [`:split`](https://neovim.io/doc/user/windows.html#:split) | `:PickerSplit` |
| [`:vsplit`](https://neovim.io/doc/user/windows.html#:vsplit) | `:PickerVsplit` |
| [`:buffer`](https://neovim.io/doc/user/windows.html#:buffer) | `:PickerBuffer` |
| [`:tjump`](https://neovim.io/doc/user/tagsrch.html#:tjump) | `:PickerTag` |
| [`:stjump`](https://neovim.io/doc/user/tagsrch.html#:stjump) | `:PickerStag` |
| [`:help`](https://neovim.io/doc/user/helphelp.html#:help) | `:PickerHelp` |

Hence there's no `:PickerVstag` just because Vim has no `:vstag` command, but I'm not opposed to adding such commands to vim-picker if they'd be useful.

**Comment by bronzehedwick** [comment]
I'd personally find them useful, especially the split buffer commands. Thanks for the explanation!

**Comment by srstevenson** [comment]
@bronzehedwick I thought about this more, and decided not to add such additional commands to vim-picker itself. It's quite easy to define them in your own vimrc, which allows arbitrary control over the window splitting. For example:
```viml
command! -bar PickerBufferSplit split | PickerBuffer
nmap <unique> <leader>pp :PickerBufferSplit<CR>
```

**Comment by bronzehedwick** [comment]
Fair enough, thanks!

**Comment by RobertAudi** [comment]
@srstevenson IMHO your example command/map only solves half of the problem. If the picker command is aborted (ie: pressing <kbd>Esc</kbd>) then you still have an extra split.

I also tried to do something like that:

```vim
:PickerBuffer | split
```

But that actually makes things worse (it opens the picker in two splits and then leaves one split open with the terminal still open but the process killed)

Considering the implementation of the `picker#Buffer` function:

```vim
function! picker#Buffer() abort
    " Run fuzzy selector to choose a buffer and call buffer on it.
    call s:PickFile(s:ListBuffersCommand(), 'buffer')
endfunction
```

We could maybe create custom Vim-based commands if the script-local functions such as `s:PickFile` and `s:ListBuffersCommand` are made public/autoloadable 🤔 

Something like this maybe:

```vim
function! picker#BufferVsplit() abort
    " Run fuzzy selector to choose a buffer and call buffer on it.
    call picker#PickFile(picker#ListBuffersCommand(), 'vert sbuffer')
endfunction
```

Or just create a new function that lets the user register Vim-based commands:

```vim
call picker#RegisterVim('BufferSplit', 'buffer', 'sbuffer')
call picker#RegisterVim('BufferVsplit', 'buffer', 'vert sbuffer')
```

Is that a good compromise?

**Comment by srstevenson** [comment]
@bronzehedwick @RobertAudi With #58, we've exposed `picker#File()` and `picker#String()` functions so you can run arbritrary Vim commands like `vert sbuffer` on your selection now.

For the example above you'd have to vendor `s:ListBuffersCommand()` though. I'm thinking about what other functions we might want to expose: I want to provide flexibility to the user, but am wary of tying them to specific implementation details that we might change later.
