### ISSUE TITLE
How to get current file name in picker#Register shell_command?

### ISSUE THREAD

**Issue by zealotrush** [srstevenson/vim-picker#54]
I'd like to register a user-defined command to find all files with the same base name with the current file (but possibly with different file extensions, and in different sub-directories), something like this:

```vim
call picker#Register('alternate', 'file', 'edit', 'find . -name <current-file-name>.*')
```

But I couldn't find a way to get the current file base name in the `shell_command` part.

**Comment by boxofrox** [comment]
Hmmmm. An interesting conundrum. Currently,  dynamic input lists are currently generated by static commands/functions (PickerBuffer, PickerTag, etc). No provision was made for the user defined commands, so how might we resolve this?

1. Custom vim callback.

User defines a callback function that takes no arguments, and returns a list of inputs for the picker. Update `picker#Register` to accept a vim callback instead of shell command.

- ✔ Flexible. User is free to call shell commands or not to generate the file list. 
- ❌ Heavier memory usage to generate list and convert to input string for picker.

Callback could generate the shell command instead of the list. 

2. Dynamic string interpolation (aka search/replace).

User can include tokens with special meaning in the shell command that are replaced by vim-picker every time the command runs. Might use `{}` to surround a vim expression or some such. 

- ✔ Less work than making a callback. 
- ❌ Less flexible than the callback. Devs must modify code to support new expressions.
- ❌ Error prone. Symbols like `{}` have special meaning to shells and may be consumed by vim-picker when the user wanted otherwise. 
- ✔Could use mustache-like templates `{{ }}` to avoid shell conflicts.

3. `picker#Run()`

Add a new function that allows the user to provide `picker#Register` arguments without the register/activate cycle. Arguments can be evaluated everytime a vim command/keybinding calls `picker#Run` and user is free to concatenate a shell command from shell expressions as they see fit.

- ✔ Same flexibility as callback without the overhead from generating a list. 
- ❌ May require use of `execute` vim command to reevaluate the vim expression.  Not my preferred syntax due to additional layer of quoting/escaping.

It's late, so my reasoning may be off.  Will reevaluate these options later.

**Comment by srstevenson** [comment]
@zealotrush With #58, you can achieve this using the `picker#File()` function now.
