### ISSUE TITLE
Keybind on selected item instead of different commands

### ISSUE THREAD

**Issue by lithammer** [srstevenson/vim-picker#8]
I wasn't really sure how to articulate this in the title. But basically, instead of having a command for every possible way to open a file (i.e. current buffer, split, vertical or tab). You'd have a keybinding that works on the selection list, similar to how [ctrlp-p](https://github.com/ctrlpvim/ctrlp.vim#once-ctrlp-is-open) or [fzf.vim](https://github.com/junegunn/fzf.vim#commands) works. So `<C-v>` to open the current selection in a vertical split, `<C-s>` for a horizontal split and `<C-t>` to open in a new tab. And just `<CR>` to open in the current buffer.

This way you only have to configure one keybind to open the search window, and _then_ you can decide _how_ you want to open the file you looked for, instead of before searching.

Does that make sense? :)

**Comment by srstevenson** [comment]
That makes perfect sense @renstrom. I considered this early on, but there were a few reasons that I went with the current model:

* within Vim we don't have Neovim's embedded terminal emulator so instead use [`systemlist()`](https://vimhelp.appspot.com/eval.txt.html#systemlist%28%29) to run the fuzzy selector. In this case the selector isn't run within a Vim buffer, so we can't define additional mappings. ctrlp.vim achieves what you suggest by implementing the fuzzy selection in Vimscript, rather than an external tool, and fzf.vim uses a feature of fzf not present in other fuzzy selectors (the `--expect` argument) to achieve this.
* The current behaviour of specifying the method of opening the file first, and choosing the filename second, is consistent with Vim's builtin commands like `:edit`, `:split`, and `:tabedit`.

That said, I'm interested to hear ideas around how this could be implemented elegantly.

**Comment by lithammer** [comment]
I ended up solving it like this, which felt very Vim-like (and using `C-p` is an old [ctrlp](https://github.com/ctrlpvim/ctrlp.vim) habit):

```vim
nnoremap <silent> <C-p> :PickerEdit<CR>
nnoremap <silent> <C-w><C-p> :PickerSplit<CR>
```

Then if I want a vertical split I could just do `<C-w>L` after.
